### ISSUE TITLE
ArgumentException in Mouse.MoveTo(Position newPosition) if distance is 0

### ISSUE THREAD

**Issue by dbtfsbre** [FlaUI/FlaUI#289]
If Mouse.MoveTo(Point newPosition) is called while the mouse is already at the target position, an Exception is thrown:

TimeSpan does not accept floating point Not-a-Number values.
       at System.TimeSpan.Interval(Double value, Int32 scale)
       at FlaUI.Core.Input.Mouse.MoveTo(Int32 newX, Int32 newY)
       at FlaUI.Core.Input.Mouse.MoveTo(Point newPosition)

**Comment by Roemer** [comment]
Haha nice find. That should be fixed in f70ab2392c65fe68527b7db5c9bc12306c23b49b.

**Comment by dbtfsbre** [comment]
The test looks good. Closing the issue.

**Comment by ChetanJB** [comment]
Getting similar issue for button click with true as parameter. Following is the exception stack.

   at System.TimeSpan.Interval(Double value, Int32 scale)
   at FlaUI.Core.Input.Mouse.MoveTo(Int32 newX, Int32 newY)
   at FlaUI.Core.Input.Mouse.MoveTo(Point newPosition)
   at FlaUI.Core.AutomationElements.AutomationElement.PerformMouseAction(Boolean moveMouse, Action action)
   at FlaUI.Core.AutomationElements.AutomationElement.Click(Boolean moveMouse)
