### ISSUE TITLE
Getting The type initializer for 'FlaUI.Core.Tools.OperatingSystem' threw an exception.

### ISSUE THREAD

**Issue by DanielRowe1** [FlaUI/FlaUI#321]
Playing around with FlaUI doing this:

 var app = FlaUI.Core.Application.Attach(process);

I am getting this exception:

`
System.TypeInitializationException : The type initializer for 'FlaUI.Core.Tools.OperatingSystem' threw an exception.
  ----> System.NullReferenceException : Object reference not set to an instance of an object.
   at FlaUI.Core.Tools.OperatingSystem.get_Is64Bit()
   at FlaUI.Core.WindowsAPI.WindowsApiTools.GetMainModuleFilepath(Process process)
   at FlaUI.Core.Application.Attach(Process process)
--NullReferenceException
   at FlaUI.Core.Tools.OperatingSystem.GetRegistryValue[T](String keyName)
   at FlaUI.Core.Tools.OperatingSystem.GetVersion()
   at FlaUI.Core.Tools.OperatingSystem..cctor()
`

Cant seem to work out what the issue is.

**Comment by Roemer** [comment]
Might be an issue with permissions? Try running the code with FlaUI elevated.

**Comment by Roemer** [comment]
Is this still an issue?

**Comment by yupengfei** [comment]
I got the same error on windows xp sp3. Here is the code
```
using FlaUI.Core;
using FlaUI.UIA2;
using System;

namespace Demo
{
    class Program
    {
        static void Main(string[] args)
        {

            var app = Application.Attach("QQ.exe");
            using (var automation = new UIA2Automation())
            {
                var window = app.GetMainWindow(automation);
                Console.WriteLine(window.Title);
                Console.ReadLine();

            }
        }
    }
}
```

**Comment by yupengfei** [comment]
I think I got the solution. On Windows XP,  this line should get CurrentBuildNumber, but it get CurrentBuild which is not a number

https://github.com/FlaUI/FlaUI/blob/master/src/FlaUI.Core/Tools/OperatingSystem.cs#L132
