### ISSUE TITLE
VideoRecorder throwing exception on a virtual machine

### ISSUE THREAD

**Issue by tnoble-accelita** [FlaUI/FlaUI#360]
The following exception occurs sporadically when running the VideoRecorder on a virtual machine.

```
build	30-Jun-2020 14:38:50	 System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Pipe hasn't been connected yet.
build	30-Jun-2020 14:38:50	    at System.IO.Pipes.PipeStream.CheckWriteOperations()
build	30-Jun-2020 14:38:50	    at System.IO.Pipes.PipeStream.Flush()
build	30-Jun-2020 14:38:50	    at FlaUI.Core.Capturing.VideoRecorder.WriteLoop()
build	30-Jun-2020 14:38:50	    at System.Threading.Tasks.Task.Execute()
build	30-Jun-2020 14:38:50	    --- End of inner exception stack trace ---
build	30-Jun-2020 14:38:50	    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
build	30-Jun-2020 14:38:50	    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
build	30-Jun-2020 14:38:50	    at FlaUI.Core.Capturing.VideoRecorder.Stop()
build	30-Jun-2020 14:38:50	 ---> (Inner Exception #0) System.InvalidOperationException: Pipe hasn't been connected yet.
build	30-Jun-2020 14:38:50	    at System.IO.Pipes.PipeStream.CheckWriteOperations()
build	30-Jun-2020 14:38:50	    at System.IO.Pipes.PipeStream.Flush()
build	30-Jun-2020 14:38:50	    at FlaUI.Core.Capturing.VideoRecorder.WriteLoop()
build	30-Jun-2020 14:38:50	    at System.Threading.Tasks.Task.Execute()<---
build	30-Jun-2020 14:38:50	 
build	30-Jun-2020 14:38:50	 One or more errors occurred.
build	30-Jun-2020 14:38:50	 System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Pipe hasn't been connected yet.
build	30-Jun-2020 14:38:50	    at System.IO.Pipes.PipeStream.CheckWriteOperations()
build	30-Jun-2020 14:38:50	    at System.IO.Pipes.PipeStream.Flush()
build	30-Jun-2020 14:38:50	    at FlaUI.Core.Capturing.VideoRecorder.WriteLoop()
build	30-Jun-2020 14:38:50	    at System.Threading.Tasks.Task.Execute()
build	30-Jun-2020 14:38:50	    --- End of inner exception stack trace ---
build	30-Jun-2020 14:38:50	    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
build	30-Jun-2020 14:38:50	    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
build	30-Jun-2020 14:38:50	    at FlaUI.Core.Capturing.VideoRecorder.Stop()
build	30-Jun-2020 14:38:50	 ---> (Inner Exception #0) System.InvalidOperationException: Pipe hasn't been connected yet.
build	30-Jun-2020 14:38:50	    at System.IO.Pipes.PipeStream.CheckWriteOperations()
build	30-Jun-2020 14:38:50	    at System.IO.Pipes.PipeStream.Flush()
build	30-Jun-2020 14:38:50	    at FlaUI.Core.Capturing.VideoRecorder.WriteLoop()
build	30-Jun-2020 14:38:50	    at System.Threading.Tasks.Task.Execute()<---
```

The setup of the VideoRecorder is as follows:
```c#
m_videoRecorder = new VideoRecorder(new VideoRecorderSettings { VideoFormat = VideoFormat.xvid, VideoQuality = 8, ffmpegPath = ffmpegPath, TargetVideoPath = videoFilePath }, r =>
{
    var testName = testTitle;
    var img = Capture.Screen();
    img.ApplyOverlays(new InfoOverlay(img)
    {
        RecordTimeSpan = r.RecordTimeSpan,
        OverlayStringFormat = @"{rt:hh\:mm\:ss\.fff} / {name} / CPU: {cpu} / RAM: {mem.p.used}/{mem.p.tot} ({mem.p.used.perc}) / " + testName,
        OverlayTextColor = Color.Red
    },
    new MouseOverlay(img));

    return img;
});
```
and the teardown
```c#
if (m_videoRecorder != null)
{
    Trace.WriteLine($"Recorder saving to -> {m_videoRecorder.TargetVideoPath}");

    filepath = m_videoRecorder.TargetVideoPath;
    m_videoRecorder.Stop();

    m_videoRecorder.Dispose();
    m_videoRecorder = null;
}
```

We also found that running with VideoFormat.x264 resulted in no videos being saved, whereas VideoFormat.xvid works more reliably. 

System info:
Windows 10 Enterprise (x64) Build 18363
16GB RAM
Running through Hyper-V (Microsoft Virtual Machine Manager)

A desktop session is available and the actual UI tests run. The problem is related simply to the VideoRecorder.

**Comment by Roemer** [comment]
That is kind of strange as I have a `WaitForConnection` on the pipe. I suppose it happens when the test is finished and it tries to write the video file?

**Comment by tnoble-accelita** [comment]
@Roemer, you are correct - it fails when the test finishes. Any thoughts?

**Comment by Roemer** [comment]
Very strange. Do you have some way to reproduce the issue?

**Comment by tnoble-accelita** [comment]
Sorry for the delay, we have been trying to track down the issue a bit more.

We have a test that causes FlaUI to throw the following exception
```
Failed applying overlay 'FlaUI.Core.Capturing.MouseOverlay'
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.FromHbitmap(IntPtr hbitmap, IntPtr hpalette)
   at System.Drawing.Image.FromHbitmap(IntPtr hbitmap)
   at System.Drawing.Icon.BmpFrame()
   at FlaUI.Core.Capturing.CaptureUtilities.CaptureCursor(Point& position)
   at FlaUI.Core.Capturing.MouseOverlay.Draw(Graphics g)
   at FlaUI.Core.Capturing.CaptureImage.ApplyOverlays(ICaptureOverlay[] overlays)
```

Once this exception occurs, no further videos are recorded. We are now able to replicate this issue on our local machines so it is not just on virtual machines (good news 👍)
