### ISSUE TITLE
No AutomationId property when running from remote

### ISSUE THREAD

**Issue by RikiSharon** [FlaUI/FlaUI#408]
**Describe the bug**
I am using FlaUI to get UI elements of my app, then I test their values in NUnit project. 
Running locally works well, but when running from remote (using PsExec) I get Null Exception.
I debugged and found that when running from remote, the elements do not have Automation Id, which should exist, and really exist when running locally. (I can see the automation ID when running FlaUIInspect)

**Code snippets**
Locally (works well, have AutomationID):
`dotnet test GuiTests.dll `

From Remote (does not work well, cannot find Automation ID):
`psexec -h  -i 1 -w C:\Users\Administrator\Tests \\%DUT_IP% -u %DUT_USER% -p %DUT_PASS% cmd /c "cd C:\Users\Administrator\Tests&&dotnet test GuiTests.dll"`

**Additional context**
When trying to find the child using Name instead of AutomationId - it worked. but this is not a real solution as the Name is being changed when the text of the Label\Button changes, there for i need an ID.

**Comment by Roemer** [comment]
That is strange as I don't see why that should not be available. Is your remote exactly the same (Windows Version for example) as your local one?

**Comment by RikiSharon** [comment]
Yes. 
They are both Windows10, Version 1803 (OS Build 17134.2026)

I tried again, when the compiled test on the Remote is getting the element using **AutomationID** - the test **fails**:
`MainForm().FindFirstDescendant("btnClose").AsButton()`

When I change the test's code to get the element using **XPath** - it **works**.
`MainForm().FindFirstByXPath("/Pane/Pane[2]/Button[2]")?.AsButton()`

(Locally, both ways work!)

I can't understand why.

**Comment by Roemer** [comment]
Do you have a chance to check with FlaUInspect on the remote on how the application looks the same there as your local one?

**Comment by RikiSharon** [comment]
When I access the testing platform itself -  FlaUInspect shows the right AutomationID.
When accessing the Remote Controller, and running FlaUInspect on the Testing Platform using PsExec - AutomationID is missing.

I tried also[ inspect.exe](https://docs.microsoft.com/en-us/windows/win32/winauto/inspect-objects), and got the same behaviour.

So I assume the issue is related to PsExec and the remote session, and not related to FlaUI.

Thanks!!

**Comment by maxinfet** [comment]
@RikiSharon If the session executing the powershell script does not have a desktop it can still spawn your process but you wont be able to access any automation elements. I would think doing `psexe` would be just like if I were to start my ui automation through an RDP then close the RDP session.

**Comment by RikiSharon** [comment]
@maxinfet , I don't think this is the use case here, because I am running PsExec with "-i 1" argument, which means: "Run the program so that it interacts with the desktop of the specified session on the remote system." (see [doc.](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec))

**Comment by maxinfet** [comment]
> @maxinfet , I don't think this is the use case here, because I am running PsExec with "-i 1" argument, which means: "Run the program so that it interacts with the desktop of the specified session on the remote system." (see [doc.](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec))
> 
> 

The only other thing I can think of is there's a registry key which controls whether a minimized RDP session will destroy the desktop view. This doesn't kill any application that is running that has a UI but it does prevent UI automation from continuing. We found this at my work because various employees when they got their new PCs would no longer be able to minimize their RDP when they were running UI automation but some of us could. 

Either way the symptoms sound the similar to what we experienced, we closed your RDP session or minimized it without the registry key. Have you tried getting all children of the desktop and all children of your application to see what it reports?  When we had both of these issues if you were to try to get all children of your window it would return nothing.

**Comment by maxinfet** [comment]
@RikiSharon Sorry it took me so long to respond to this, I completely forgot about it. So the registry key I was thinking of was `HKEY_CURRENT_USER\Software\Microsoft\Terminal Server Client` and the DWORD is `RemoteDesktop_SuppressWhenMinimized` with a value of 2. I am not sure this would be needed for PsExec usage but it is worth a shot to see if it helps with the issue you are running into. Here are the steps we follow for setting this for each of the machines we run our UIA on.

1. Close all open RDP sessions
2. Launch Registry Editor (regedit.exe)
3. Navigate to HKEY_CURRENT_USER\Software\Microsoft\Terminal Server Client
4. Create a DWORD value named RemoteDesktop_SuppressWhenMinimized and set it to 2
5. Close Registry Editor

**Comment by RikiSharon** [comment]
@maxinfet, Thanks for trying to help.
I added the regisrty you wrote, but no success. I still get NullException.

**Comment by maxinfet** [comment]
@RikiSharon No problem, when I get the chance I will try how you are running with our UI automation but not sure how long it will take before I can get to that. I will give you the heads up on what I find.

**Comment by igorrecioh** [comment]
I am having similar issue. I am trying to run my tests in a machine with RDP. When RDP window is visible (I can see the test running) there is no problem, tests run as expected. However, if I run tests and then I minimized the RDP window, all tests fail and I get always this error:

```bash
Error Message:
   System.ComponentModel.Win32Exception : Access is denied.
  Stack Trace:
     at FlaUI.Core.Input.Mouse.SendInput(Int32 x, Int32 y, UInt32 data, MouseEventFlags flags)
   at FlaUI.Core.Input.Mouse.Down(MouseButton mouseButton)
   at FlaUI.Core.Input.Mouse.Click(MouseButton mouseButton)
   at FlaUI.Core.Input.Mouse.LeftClick()
   at FlaUI.Core.AutomationElements.AutomationElement.PerformMouseAction(Boolean moveMouse, Action action)
   at FlaUI.Core.AutomationElements.AutomationElement.Click(Boolean moveMouse)
```

Am I doing something wrong?

**Comment by igorrecioh** [comment]
Hmm I can see this:
https://github.com/FlaUI/FlaUI/issues/151#issuecomment-375650514

The problem is that I am trying to do click... I will try to avoid that but it is a button so I may use VLC is possible

**Comment by igorrecioh** [comment]
Using VNC solved the problem in my case. Now I can run automated tests with FlaUI even if I minimize the VNC window.
