### ISSUE TITLE
Problematic Usage of GetMainWindow for Attached Process

### ISSUE THREAD

**Issue by OndrejVicar** [FlaUI/FlaUI#414]
`Application.GetMainWindow` Disposes Application`s process even if it is already running and ready.  It happens in https://github.com/FlaUI/FlaUI/blob/0213614a16da1517a6160e00c07cd5c0c0567767/src/FlaUI.Core/Application.cs#L234-L242 I don't think Process should be Disposed like that.  It could be problematic in some scenarios. 

Consider following code. Here I have very simple `winforms` app I want to test. This app also produces some output to stdout so I want to redirect it into the test environment (`winforms` example produces int increments)

```csharp
using System;
using System.Diagnostics;
using FlaUI.Core;
using FlaUI.UIA3;

var processStartInfo = new ProcessStartInfo("winforms")
{
    RedirectStandardOutput = true,
};

var process = new Process
{
    StartInfo = processStartInfo
};

process.OutputDataReceived += (obj, args) => Console.WriteLine(args.Data);
process.Start();
process.BeginOutputReadLine();

System.Threading.Thread.Sleep(1000); // stdout being produced

var application = Application.Attach(process);
var window = application.GetMainWindow(new UIA3Automation()); // this will Dispose process, stdout of winforms will stop
Console.WriteLine(window.Title);

process.WaitForExit(); // any interaction with process will throw System.InvalidOperationException: No process is associated with this object
```

sample output:
```
dotnet run --project .\flaui-repro\flaui-repro.csproj
1
2
3
4
5
6
7
8
9
Form1
Unhandled exception. System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
   at <Program>$.<Main>$(String[] args) in C:\Users\ondra\git\flaui-repro\flaui-repro\Program.cs:line 28
```

Example repository: https://github.com/OndrejVicar/flaui-repro

**Comment by Roemer** [comment]
Hmm good point. The problem is that the current implementation of retry always runs the method at least once and only then does the check. For the case here, we would need a retry which first checks the condition and then does a retry. This does not work currently as currently, the check relies on the return value of the retry method. Alternatively, we could do an early-exit in the `WaitWhileMainHandleIsMissing` method in case the `MainWindowHandle` is not `Zero`.

**Comment by Roemer** [comment]
I'm in general not really proud of the `Application` class. It might be worth re-thinking and re-writing it.
