### ISSUE TITLE
i found an exception with UIA3, how to fix it.  fail rate: 1/20

### ISSUE THREAD

**Issue by Lanceliyp** [FlaUI/FlaUI#532]
**Describe the bug**
Describe what you tried and what did not work as expected.
 Exception Catched:
System.Runtime.InteropServices.COMException (0x80131505): Operation timed out. (Exception from HRESULT: 0x80131505)
   at Interop.UIAutomationClient.IUIAutomationElement.FindFirst(TreeScope scope, IUIAutomationCondition condition)
   at FlaUI.UIA3.UIA3FrameworkAutomationElement.FindFirst(TreeScope treeScope, ConditionBase condition)
   at FlaUI.Core.AutomationElements.AutomationElement.FindFirstDescendant(Func`2 conditionFunc)
**Code snippets**
   var app = Application.Launch(uninstallTool);
                Thread.Sleep(500);
                while (ProcessHelper.ProcessExist(pros))
                {
                    using (var automation = new UIA3Automation())
                    {
                        var window = app.GetMainWindow(automation);
                        var buttonNo = window.FindFirstDescendant(cf => cf.ByAutomationId("7"))?.AsButton();
                        if (buttonNo != null)
                        {
                            var text = window.FindFirstDescendant(cf => cf.ByAutomationId("65535"));
                            if (text != null)
                            {
                                Log4NetHelper.WriteLog(LogTypeEnum.INFO, $"[{text.Name}]");
                            }
                            Log4NetHelper.WriteLog(LogTypeEnum.INFO, $"Click Button [{buttonNo?.Name}]");

                            buttonNo?.Invoke();
                        }
                        Thread.Sleep(100);
                        var button1 = window.FindFirstDescendant(cf => cf.ByAutomationId("1"))?.AsButton();
                        if (button1 != null)
                        {
                            var text = window.FindFirstDescendant(cf => cf.ByAutomationId("65535").Or(cf.ByAutomationId("1001")));
                            if (text != null)
                            {
                                Log4NetHelper.WriteLog(LogTypeEnum.INFO, $"[{text.Name}]");
                            }
                            Log4NetHelper.WriteLog(LogTypeEnum.INFO, $"Click Button [{button1?.Name}]");
                            button1?.Invoke();
                        }
                        Thread.Sleep(100);
                    }
                }

**Comment by teejo75** [comment]
I'm having the same issue. It's intermittent. It will work perfectly one run, then randomly throw the exception on a subsequent run.
The call is wrapped in Retry.WhileNull with a long timeout, but when this exception throws it's long before the Retry.WhileNull timeout.

I'm not sure if this is specific to FlaUI.UIA3 v4.0.0. I'm going to try downgrading back to 3.2.0 and see if it still occurs.

```
System.Runtime.InteropServices.COMException (0x80131505): Operation timed out. (0x80131505)
   at Interop.UIAutomationClient.IUIAutomationElement.FindFirst(TreeScope scope, IUIAutomationCondition condition)
   at FlaUI.UIA3.UIA3FrameworkAutomationElement.FindFirst(TreeScope treeScope, ConditionBase condition)
   at FlaUI.Core.AutomationElements.AutomationElement.FindFirst(TreeScope treeScope, ConditionBase condition)
   at FlaUI.Core.AutomationElements.AutomationElement.FindFirstChild(ConditionBase condition)
   at FlaUI.Core.AutomationElements.AutomationElement.FindFirstChild(Func`2 conditionFunc)
   at XXXX.MainForm.<>c__DisplayClass76_0.<TaskXXXX>b__12()
   at FlaUI.Core.Tools.Retry.While[T](Func`1 retryMethod, Func`2 checkMethod, Nullable`1 timeout, Nullable`1 interval, Boolean throwOnTimeout, Boolean ignoreException, String timeoutMessage, Boolean lastValueOnTimeout, T defaultOnTimeout)
   at FlaUI.Core.Tools.Retry.WhileNull[T](Func`1 checkMethod, Nullable`1 timeout, Nullable`1 interval, Boolean throwOnTimeout, Boolean ignoreException, String timeoutMessage)
   at XXXX.MainForm.TaskXXXX()
   at XXXX.MainForm.btnRun_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```
