### ISSUE TITLE
FlaUI.UIA2 cannot find UIAutomationClient when running on headless build agent

### ISSUE THREAD

**Issue by zenntenn** [FlaUI/FlaUI#553]
**Describe the bug**
When trying to run automation for FlaUI.UIA2 package version 4.0.0 on a self-hosted Azure DevOps build agent I get the error: System.IO.FileNotFoundException : Could not load file or assembly 'UIAutomationClient, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

Stack Trace:
at FlaUI.UIA2.UIA2PatternLibrary.get_DockPattern()
at FlaUI.UIA2.UIA2PatternLibrary.get_AllForCurrentFramework()
at FlaUI.Core.AutomationBase..ctor(IPropertyLibrary propertyLibrary, IEventLibrary eventLibrary, IPatternLibrary patternLibrary, ITextAttributeLibrary textAttributeLibrary)
at FlaUI.UIA2.UIA2Automation..ctor()
[at FunctionalTests.Tests.Setup() in \TAFCSharp\FunctionalTests\Tests.cs:line 43]

**Code snippets**
var application = Application.Launch(ExecutablePath);
var automation = new UIA2Automation();

**Additional context**
When running the code locally on my machine it works fine.

Adding the NuGet package Interop.UIAutomationClient makes no difference

**Comment by zenntenn** [comment]
Both my workstation, and the build agent server both have the exact same path and DLL version:

C:\Windows\Microsoft.NET\assembly\GAC_MSIL\UIAutomationClient\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationClient.dll
Version 4.8.9139.0

**Comment by Pianykh** [comment]
Greetings! I faced the same problem. Did you manage to solve it?

**Comment by Pianykh** [comment]
@zenntenn 
Greetings! I faced the same problem. Did you manage to solve it?
