### ISSUE TITLE
Application fails to launch in github action, cannot find process with ID

### ISSUE THREAD

**Issue by Machtap** [FlaUI/FlaUI#647]
**Describe the bug**
The following code invoking FLAUI tests works in local development environment but fails when invoked through a github action runner

**Code snippets**
```
[OneTimeSetUp]
    public async Task SetupApplication()
    {

        App = Application.Launch(AppPath, "FLAUI-Test");
        await Task.Delay(TimeSpan.FromSeconds(5));
        App.WaitWhileMainHandleIsMissing();
        Automation = new UIA3Automation();
        Window = App.GetMainWindow(Automation);

    }
```

**Github Action output**
```Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Setup failed for test fixture E2ETests.DashboardPageTests
System.Exception : Could not find process with id: 3024
  ----> System.ArgumentException : Process with an Id of 3024 is not running.
StackTrace:    at FlaUI.Core.Application.FindProcess(Int32 processId)
   at FlaUI.Core.Application.<WaitWhileMainHandleIsMissing>b__33_0()
   at FlaUI.Core.Tools.Retry.<>c__DisplayClass_0.<WhileTrue>b__0()
   at FlaUI.Core.Tools.Retry.While[T](Func`1 retryMethod, Func`2 checkMethod, Nullable`1 timeout, Nullable`1 interval, Boolean throwOnTimeout, Boolean ignoreException, String timeoutMessage, Boolean lastValueOnTimeout, T defaultOnTimeout)
   at FlaUI.Core.Tools.Retry.WhileTrue(Func`1 checkMethod, Nullable`1 timeout, Nullable`1 interval, Boolean throwOnTimeout, Boolean ignoreException, String timeoutMessage)```

I have tried both windows-2019 and windows-2022 runners and both produce this same output which seems to be identifying a process ID but failing to attach to it?

**Comment by aidan-mcarthur-tfs** [comment]
I'm seeing the same thing in Azure DevOps. The app I'm testing is my own WPF app, not a Windows Store App, which other similar issues posted here mention.

**Comment by czdietrich** [comment]
Just some guessing here.

Usually starting an application with UI needs an interactive user session which might not be present on your build agent environment. In Azure DevOps there is a specific option for agent pools:

![image](https://github.com/user-attachments/assets/ce09c79e-781f-42e7-8202-cb80c19a9b1c)

But I have no idea how this works for GitHub Actions.

I think you could at least test, whether `Environment.UserInteractive` returns true or false.
I hope this helps a bit for your problem and isn't completely unrelated to the issue you're facing.

**Comment by jbe2277** [comment]
I'm running UI tests with FlaUI on a GitHub runner (windows-2022) for my open-source project **Win Application Framework (WAF)**.
- Three WPF applications are tested
- The applications and the UI tests are using .NET 8
- Note: GitHub actions on Windows are executed with an interactive user by default.

**GitHub Action Workflow:** 
- https://github.com/jbe2277/waf/blob/master/.github/workflows/System.Waf.CI.yml

```yml
- name: 🖥️ UI Test
  run: |
    echo "## 🕵️ Test Results - Samples.UITest.sln" >> $Env:GITHUB_STEP_SUMMARY
    dotnet test ./src/Samples.UITest/Samples.UITest.sln --logger GitHubActions -maxCpuCount:1
```

**UI test solution:**
- https://github.com/jbe2277/waf/tree/master/src/Samples.UITest

**Actions result:**
- https://github.com/jbe2277/waf/actions/workflows/System.Waf.CI.yml?query=branch%3Amaster
