### ISSUE TITLE
Unable to enter text using Robot Framework - FlaUI Keyword Library

### ISSUE THREAD

**Issue by Jaanz03** [FlaUI/FlaUI#654]
**Describe the bug**
Unable to enter text using Robot Framework Keyword  "Set Text To Textbox"

**Code snippets**
Set Text To Textbox   //Edit[@Name="Enter your email"]         xyz@abc.com

**Screenshots**
![image](https://github.com/user-attachments/assets/f4e55a78-0ea5-4c4e-a026-2e9a30cb335a)

**Additional context**
NotImplementedException: The method or operation is not implemented.
   at Interop.UIAutomationClient.IUIAutomationValuePattern.SetValue(String val)
   at FlaUI.Core.Tools.Com.Call(Action nativeAction)
   at FlaUI.Core.AutomationElements.TextBox.set_Text(String value)

**Comment by igorrecioh** [comment]
Hi @Jaanz03, as you are using FlaUI via RobotFramework you should ping to https://github.com/GDATASoftwareAG/robotframework-flaui
